controllers:
    resource: ../src/Controller/
    type: attribute
search_by_article:
    path: /search-by-article
    controller: App\Controller\ProductController::searchByArticle
    methods: ['GET']
 App\Controller\ProductController:
        arguments:
            $apiKey: '%kakoj-to-api'